### ISSUE TITLE
Using Kcache as a replicated cache

### ISSUE THREAD

**Issue by deveshprobus** [rayokota/kcache#137]
I am thinking of using kcache as a replicated cache in my application where all my instances would have the whole copy of the cache. In the docs it says that kcache may have problems using as a replicated cache in terms of ordering of updates, but in my application when considering a context of few seconds, even if there are updates from multiple instances they are of same key value pair. So I think it won't be a problem for me. I wrote a test code and all key value pairs get replicated to each instance correctly. Can I really face some issues regarding this in production with the cache?

I am adding my test code below

String bootstrapServers = "localhost:9092";
        Properties props = new Properties();
        props.put(KafkaCacheConfig.KAFKACACHE_BOOTSTRAP_SERVERS_CONFIG, bootstrapServers);
        props.put(KafkaCacheConfig.KAFKACACHE_GROUP_ID_CONFIG, "cache-test");
        props.put(KafkaCacheConfig.KAFKACACHE_TOPIC_CONFIG, "cache-test");
        props.put(KafkaCacheConfig.KAFKACACHE_CLIENT_ID_CONFIG, "test-cache-client");
        Cache<String, String> cache = new KafkaCache<>(new KafkaCacheConfig(props), Serdes.String(), Serdes.String());
        cache.init();
        while (true) {
            System.out.println("ENTER KEY");
            Scanner in = new Scanner(System.in);
            String s = in.nextLine();
            System.out.println("ENTER VALUE");
            String value = in.nextLine();
            LocalDateTime start = LocalDateTime.now();
            String output = cache.get(s);
            System.out.println("DUARATIONGET:: " + Duration.between(start, LocalDateTime.now()).toMillis());
            start = LocalDateTime.now();
            cache.put(s, value);
            System.out.println(output);
            System.out.println("DUARATIONPUT:: " + Duration.between(start, LocalDateTime.now()).toMillis());
        }

**Comment by rayokota** [comment]
If updates are idempotent (such as when the same key always maps to the same value), then it should be fine to use KCache in this manner.

**Comment by deveshprobus** [comment]
Thanks for the reply. Within a few minutes, same key is always mapped to same value from all instances. But after a few minutes one of the instances could update it to other value. Could there be a problem in that scenario? Also, for replication do I have to do anything extra, or just using the code as above should suffice?

**Comment by rayokota** [comment]
It sounds like this should be fine.  You don't have to do anything extra.

**Comment by deveshprobus** [comment]
Would the client id be same across the instances or would it be unique for each instance?

**Comment by deveshprobus** [comment]
In logs it says Creating the topic cache-test using a replication factor of 1, which is less than the desired one of 3.
I have set props.put(KafkaCacheConfig.KAFKACACHE_TOPIC_REPLICATION_FACTOR_CONFIG, 3);
