### ISSUE TITLE
Leader election with Kafka?

### ISSUE THREAD

**Issue by cricket007** [rayokota/kcache#26]
In the README

> The leader election is outside of KCache but can be implemented using ZooKeeper, for example

Could that be done in Kafka itself? Similarly to the Schema Registry, I guess?

Ref. https://www.youtube.com/watch?v=MmLezWRI3Ys

**Comment by rayokota** [comment]
Yes, you are right.  KarelDB uses Kafka for leader election.

https://github.com/rayokota/kareldb/blob/master/kareldb-server/src/main/java/io/kareldb/server/leader/KarelDbLeaderElector.java

**Comment by cricket007** [comment]
KarelDB, sure, but KCache uses that?

**Comment by rayokota** [comment]
That's just an example.  KarelDB uses KCache.  You could do something similar.
