### ISSUE TITLE
question about topic setup

### ISSUE THREAD

**Issue by junhuhdev** [rayokota/kcache#263]
Hi thanks for great work of this library. 

Question what do u recommend on the number of topics creation? 

Initially i thought to have one global topic, and then each key in event can be defined uniquely by each app. But this would eventually lead to big memory foot print. 

So I guess a better approach would be to create a topic per application and environment?

**Comment by rayokota** [comment]
You can also use a a persistent cache such as RocksDB to back `KafkaCache`, in order to reduce the memory footprint.
