### ISSUE TITLE
Check for compacted topic does not account for "cleanup.policy=compact,delete"

### ISSUE THREAD

**Issue by rvertigo** [rayokota/kcache#33]
**Use case:**
- An expiring localCache implementation, like caffeine or guava, can be paired with a `cleanup.policy=compact,delete` topic that will expire old entries. This will result in the option to have a Kafka-backed LRU-style cache.

**Issue:**
- `KafkaCache.verifyTopic(...)` throws (or logs WARN) when a cache topic is configured to `cleanup.policy=compact,delete`

**Documentation:**
- From [Kafka log.cleanup.policy](https://kafka.apache.org/documentation.html#cleanup.policy):
> A string that is either "delete" or "compact" or both

**Proposed Solution:**
- Since the policy can include _both_ compact and delete, the topic verification should validate that the policy _includes_ compact, not only that it equals compact.

https://github.com/rayokota/kcache/blob/d4db01cdcfd6dddfefff16627943796e6f7f2c57/src/main/java/io/kcache/KafkaCache.java#L346-L359

**Comment by rayokota** [comment]
You can set `kafkacache.topic.require.compact` as `false` (in which case you'll get a warning).

**Comment by rvertigo** [comment]
Thanks for the workaround, I mentioned it in the description. It logs a warning, but it wouldn't need to.

**Comment by rayokota** [comment]
I also added `kafkacache.topic.skip.verify` which will skip topic verification altogether.
