### ISSUE TITLE
KCache vs KTable / Replicated caches

### ISSUE THREAD

**Issue by gtrefs** [rayokota/kcache#43]
Thank you very much for KCache. I have learned quite a lot by looking into the code. Actually this is not an issue but more like some questions for a better understanding. 

I was wondering how KCache compares to a KTable / GlobalKTable. Like KCache, a KTable can be backed by a store like RocksDB which allows me to query for a specific value. Updating the values is a bit cumbersome in a KTable compared to KCache as one needs to write to the corresponding topic. Are there other differences I am not aware of? 

Further, I am not sure if I understand the limitation of using KCache as a replicated cache. Does it mean, that there should only be one instance/application writing to the cache while there can be multiple consumers? In my use case, I would like to write some configuration properties to a log-compacting topic with multiple readers. For resilience purposes I wanted to replicate the writer. Does this mean, I need to do the leader election on my own?

**Comment by gtrefs** [comment]
Thanks for the answer. Can you explain why there should only be one leader? Is this a use case of the [Single Writer Principle](https://softwareengineering.stackexchange.com/questions/309339/understanding-the-single-writer-principle)?

**Comment by rayokota** [comment]
Yes, having a single writer helps prevent out-of-order updates, for example if one or more clients send updates to the same key that land on different nodes.  Without a single leader, the updates could be persisted in a different order than the order in which they were sent.
