### ISSUE TITLE
Possible to create a persistent cache that doesn't depend on the filesystem?

### ISSUE THREAD

**Issue by aelfric** [rayokota/kcache#475]
I'm using a LocalCache backed by a database for a read-only cache for the sake of speeding up startup time, but the process itself is running in an ephemeral container where it is not possible to write Kafka offsets to a file. Because of this, I have a custom local cache implementation rather than the built-in RDBMS implementation where `isPersistent` is false.  It seems like it would make sense to have, for example, the RDBMS local cache manage the committed offsets rather than the filesystem where the cache is running.  I can see from the code it would require some refactoring, but would something like adding offset management to the LocalCache interface make sense?

**Comment by rayokota** [comment]
@aelfric , in the next release you'll be able to set `kafkacache.checkpoint.handler` to a class that implements `io.kcache.CheckpointHandler`

**Comment by aelfric** [comment]
This is great. Thanks for making the change. I wasn't expecting so quick a response. Do you have a release date planned?

**Comment by rayokota** [comment]
@aelfric , I've released 5.1.0
