### ISSUE TITLE
Add a possibility to work with topics where cleanup.policy is delete not only compact

### ISSUE THREAD

**Issue by Yambui** [rayokota/kcache#6]
Now for the purpose of data saving, there is a strict check if Kafka topic has cleanup.policy=compact, otherwise, Exception is thrown and the application fails.  I think it will be a great idea to add some flag, and if I agree with possible data loss I can work with a topic which has cleanup.policy=delete too. It will be good for educational purposes because you could not create topics with compact policy on free Kafka online services.

**Comment by gvlachogiannis** [comment]
I agree, I have exactly a use case where I don't care for very old data. I want to track the login users of a system, and the user usually logout or the login expires (inactivity) after a few hours.

**Comment by rayokota** [comment]
Added config `kafkacache.topic.require.compact` which you can set to `false`

**Comment by deveshprobus** [comment]
Does the manually created topic in this case has to be single partition or can it have multiple partitions?

**Comment by rayokota** [comment]
It can have multiple partitions.
