### ISSUE TITLE
Is there a way to set Kafka Producer specific properties in KCache?

### ISSUE THREAD

**Issue by ankitashome** [rayokota/kcache#92]

**Comment by ankitashome** [comment]
I would like to set Kafka Producer specific properties,  E.g: compression.type, linger.ms, batch.size etc. in KCache. Could not find any config properties for that. Is there a way to do?

**Comment by rayokota** [comment]
Just prefix the properties with `kafkacache.`, for example, `kafkacache.compression.type`
