### ISSUE TITLE
Need some understanding on writing data from Multiple JVMs

### ISSUE THREAD

**Issue by amit2103** [rayokota/kcache#98]
Hey @rayokota ,

Thanks for the awesome library.  We are planning to use it in production.

However in our case we want to sync data from various JVms (each running an instance of Kcache).
My question is what is the con :- Is it that we may get an older version of data as the latest ?

Secondly what happens when we use a separate producer to send data to the same Kafka topic KCache is reading from. Will that work ?

Regards

**Comment by rayokota** [comment]
If you use multiple instances of KCache (or a producer) to write to the same topic, then it will be more difficult to reason about the order in which the writes occurred.  However, if you don't rely on order, then it shouldn't be a problem.
